### ISSUE TITLE
Reset focus on routing

### ISSUE THREAD

**Issue by johannesholmberg** [gridsome/gridsome#1191] opened 2020-05-26 08:12 UTC
## Summary

I’ve realized that keyboard focus is not resetting while routing to a new page. 

Take for instance a footer navigation which you’re using the keyboard to navigate. If you navigate to one of the links, the focus is still on that link in the footer after the page has loaded. Which means I can’t tab through the new page from the start of the document, but it instead keeps tabbing through the footer nav.

Maybe there is already an option for how to do this? Any help would be very appreciated.

**Comment by a-kriya** [comment] 2020-05-26 13:50
Cannot reproduce on my built site. Are you noticing this behavior during dev, in the build, or both? Does your Layout component (that wraps all pages) include the footer, or is it outside the layout? Are you using `keep-alive` anywhere?

**Comment by johannesholmberg** [comment] 2020-05-27 18:31
Thanks for the quick return. I’m not using `keep-alive` anywhere. I keep my header and footer in App.vue (which is above the Layout component) and I realized this is probably the reason. Moving them into the layout solves it.

**Comment by a-kriya** [comment] 2020-05-27 19:53
@johannesholmberg Okay, great. Since routing after hydration would not re-create elements outside the page layout, they retain focus.

Would you mind closing the ticket?

**Closed** 2020-05-28 07:02 UTC
