### ISSUE TITLE
Images are not absolute path in final build

### ISSUE THREAD

**Issue by raygervais** [gridsome/gridsome#1022] opened 2020-03-03 03:30 UTC
## Description

Images are using relative paths, which cause issues in website aggregates such as https://github.com/Seneca-CDOT/telescope/issues/774.

### Steps to reproduce

This can be seen by inspecting the cover_image of any post on my site. https://raygervais.dev/article/reduced-container-sizes-with-multi-stage-docker-builds/

### Expected result

image source should be absolute path, coming from `raygervais.dev` so that other sites can pickup the absolute path.

### Actual result

```html
<img alt="Cover image" src="/assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.07cc2b7.dc7372eb230e70039d4d363df4472818.jpg" data-src="/assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.07cc2b7.dc7372eb230e70039d4d363df4472818.jpg" data-srcset="/assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.a67b0b2.dc7372eb230e70039d4d363df4472818.jpg 480w, /assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.07cc2b7.dc7372eb230e70039d4d363df4472818.jpg 860w" data-sizes="(max-width: 860px) 100vw, 860px" class="g-image g-image--lazy g-image--loaded" srcset="/assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.a67b0b2.dc7372eb230e70039d4d363df4472818.jpg 480w, /assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.07cc2b7.dc7372eb230e70039d4d363df4472818.jpg 860w" sizes="(max-width: 860px) 100vw, 860px" width="860">
```

What happened.

### Environment

Paste the information here as shown by `gridsome info`
```


  System:
    OS: Linux 5.3 Pop!_OS 19.10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    npm: 5.8.0 - /usr/bin/npm
  Browsers:
    Firefox: 73.0.1
  npmPackages:
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
    @gridsome/remark-prismjs: ^0.2.0 => 0.2.0 
    @gridsome/source-filesystem: ^0.6.0 => 0.6.2 
    @gridsome/transformer-remark: ^0.3.0 => 0.3.4 
    gridsome: ^0.7.13 => 0.7.13 
    gridsome-plugin-feed: ^1.0.2 => 1.0.2 
```

**Comment by mtlynch** [comment] 2020-05-31 15:05
Thanks for submitting this @raygervais. Other sites can reference any image on your site by simply prepending your domain to the relative path. 

If I right click > "Open in new tab" on the cover image in the referenced post, I see this:

```
https://raygervais.dev/assets/static/pawel-czerwinski-f_sUgtC7lV0-unsplash.07cc2b7.dc7372eb230e70039d4d363df4472818.jpg
```

Closing this as wontfix for now, as this is intended behavior. If I'm misunderstanding, please let me know which scenarios are possible with an absolute path that are not possible with a relative path.

**Closed by mtlynch** 2020-05-31 15:05 UTC
Labels: wontfix
