### ISSUE TITLE
built with Gridsome page?

### ISSUE THREAD

**Issue by Maxhodges** [gridsome/gridsome#842] opened 2019-11-29 14:46 UTC
## Summary

Do you have a Built with Gridsome page? We'd look good on one!

https://beta.blackship.com

**Comment by tomtev** [comment] 2019-11-29 14:58
No showcase yet, but we have this thread #210 :)

**Comment by zacnomore** [comment] 2020-02-13 14:42
Closing as a duplicate of #210

**Closed by zacnomore** 2020-02-13 14:42 UTC
