### ISSUE TITLE
Fetching external data

### ISSUE THREAD

**Issue by arttemiuss43** [gridsome/gridsome#253] opened 2019-03-07 18:13 UTC
When I fetch external data from an API and if some graphql field consists of empty value or empty array I get the following error: `Cannot query field "level" on type "Course"`. Is this behaviour expected? And can some field be an array or I should create a reference to a collection?

**Comment by hjvedvik** [comment] 2019-03-08 09:35
That is the expected behavior because Gridsome isn't able to know which type the list will contain. We are going to open APIs for defining your own schema sometime before we release `1.0`, but it's not ready yet.

And yes, you can have an array of references like this:

```js
collection.addNode({
  fields: {
    items: itemsFromApi.map(item => {
      // Reference a node with typeName 'Item'
      return store.createReference('Item', item.id)
    })
  }
})
```

Or if the array contains only ids:

```js
// Let the 'items' field reference nodes with typeName 'Item'
collection.addReference('items', 'Item')

collection.addNode({
  fields: {
    items: ['1', '2', '3', ...]
  }
})
```

**Comment by robaxelsen** [comment] 2019-03-08 10:02
Closing, as OPs question has been answered. @arttemiuss43: feel free to reopen if you have further questions.

**Comment by arttemiuss43** [comment] 2019-03-08 11:38
Thank you:)

**Comment by arttemiuss43** [comment] 2019-03-11 08:09
When I add custom fields to content type I get the same error (`Cannot query field "*" on type "*"`) in case there are no nodes in this content type. It works well with predefined fields like title and content though. How can I avoid that?

**Comment by robaxelsen** [comment] 2019-03-14 09:06
@arttemiuss43 I suspect you have to add a custom field with addSchemaField first. [See documentation.
](https://gridsome.org/docs/data-store-api)
@hjvedvik could you please chime in here, maybe with an example?

**Closed** 2019-04-07 15:39 UTC
Labels: question
