### ISSUE TITLE
Support Wordpress 5.5

### ISSUE THREAD

**Issue by ngoclx** [gridsome/gridsome#1365] opened 2020-10-19 22:46 UTC
Do you have any plan to support WP5.5?

**Comment by hacknug** [comment] 2020-10-23 10:58
Did anything related to the API change?

**Comment by ngoclx** [comment] 2020-10-24 16:10
It's about the gutenberg in wp5.5

https://github.com/gridsome/gridsome/issues/1134

**Comment by hacknug** [comment] 2020-10-24 17:45
Closing due to duplicate of #1134.

**Closed by hacknug** 2020-10-24 17:45 UTC
