### ISSUE TITLE
Don't code-split CSS as default

### ISSUE THREAD

**Issue by tomtev** [gridsome/gridsome#230] opened 2019-02-28 23:09 UTC
## Description
Gridsome is currently code-splitting the CSS in components. This causes many errors when gridsome runs as a SPA. There is no way to control the order of when CSS files are loaded, so you get many weird CSS glitches depending on what page you enter the site.

There should be an option for those who want to continue to use code-splitting.

**Comment by awulkan** [comment] 2019-03-02 11:07
How do we ensure that the css in added in the exact right order in the final css file (if even possible)? Since css by its very definition is cascading, it matters which order styles ends up in when compiled into a file.

This can cause differences in the dev and prod version of the site.

The only way I can come up with to solve it appears to be to write very fool-proof css with loads on inheritance to make it cascade in the right order, regardless of the lexical order it's in.

**Comment by hjvedvik** [comment] 2019-03-02 11:18
webpack compiles CSS in the order it comes across it while traversing the JS code. What we have done in Gridsome is to import files in this order internally: first all plugins, then `main.js` then routes. I've done a few tests and the CSS in pages or components overrides global CSS imported in `main.js` in dev and prod. I think that would be the expected behavior. Not sure what else we can do, but any input on this would be appreciated.

**Comment by awulkan** [comment] 2019-03-02 11:38
The only solution I can think of is to make the css inlined into each component, with maybe an auto-generated prefix to each class name for that component, but that's not very elegant. It would probably prevent duplication and clashes of classes though.

**Comment by awulkan** [comment] 2019-03-02 20:22
Let's say that component A and B both contain a class with the same name. How will this conflict be handled when merging it all into one file?

I think it's a real problem that will occur a lot, especially on larger sites where you're dealing with loads of components. Of course it can be solved by using unique class names in every component, but I highly doubt most developers do that (based on what I've seen). And the `scoped` attribute on the styles in Vue will cause a sense false safety, since it won't work when all styles are merged into one file anyway.

**Comment by hjvedvik** [comment] 2019-03-02 21:07
Scoped styles will still work as expected :)

**Comment by awulkan** [comment] 2019-03-10 21:32
It says that this was added to 0.5.5, but I still face this problem.
My css overrides previous css with the same class names as I navigate the site.

**Comment by hjvedvik** [comment] 2019-03-10 21:57
@awulkan Does the `build` command generate multiple CSS files in your project?

**Comment by awulkan** [comment] 2019-03-10 22:13
@hjvedvik Sorry, didn't think about the difference between the development and build environment. This only happens during development. In the built site the css is overwritten everywhere, even though I use scoped css. Which I guess is also wrong? Since you said it would respect scoped styles.

**Comment by hjvedvik** [comment] 2019-03-11 12:04
@awulkan Good. I'll close this issue :)

**Closed by hjvedvik** 2019-03-11 12:04 UTC
Labels: feature request
