### ISSUE TITLE
Error: Field "published" is not defined by type PostFilterInput.

### ISSUE THREAD

**Issue by AlexRoidl** [gridsome/gridsome#718] opened 2019-09-30 15:13 UTC
## Description

```bash
ERROR  Failed to compile with 1 errors                                                  4:50:58 PM

 error  in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Field "published" is not defined by type PostFilterInput.

GraphQL request:16:28
15 | query {
16 |   posts: allPost(filter: { published: { eq: true }}) {
   |                            ^
17 |     edges {
    at Object.module.exports (/Users/alexroidl/hhs/my-gridsome-site/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-353 1:369-372 1:374-724 1:374-724
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
```

### Steps to reproduce

I install the example and when I run `gridsome develop` I get this error message.

### Expected result

The development environment should be started at localhost

### Actual result

ERROR

### Environment

macOS
gridsome@0.7.4

**Comment by hjvedvik** [comment] 2019-10-01 13:42
Which example/starter did you install?

**Comment by AlexRoidl** [comment] 2019-10-01 14:55
https://github.com/gridsome/gridsome-starter-blog

**Comment by csabaxyz** [comment] 2020-04-26 01:50
I think, I have the same issue. I've been trying to debug this, but didn't get too far.

In my case it is not a persistent error, only happens sometimes.

One thing I did was that I put a `console.log` here:
https://github.com/gridsome/gridsome/blob/5972339e3a3de240ea76c605f92ae87369dddba5/gridsome/lib/graphql/nodes/index.js#L38

And what I saw is that the `typeComposer` doesn't always has all the data. When the error happens then only the `id` is included in the `_gqcFields` object:
```
_gqcFields: { id: { type: [NonNullComposer] } }
```

But when everything works, it looks like this:
```
  _gqcFields: {
    id: { type: [NonNullComposer] },
    sourceUrl: {
      type: [ScalarTypeComposer],
      args: {},
      resolve: [Function: resolve],
      extensions: [Object]
    },
    dateLive: {
      type: [ScalarTypeComposer],
      args: [Object],
      resolve: [Function: resolve],
      extensions: [Object]
    },
    isYoutube: { type: [ScalarTypeComposer], args: {}, extensions: [Object] },
    videoTitle: {
      type: [ScalarTypeComposer],
      args: {},
      resolve: [Function: resolve],
      extensions: [Object]
    },
    description: {
      type: [ScalarTypeComposer],
      args: {},
      resolve: [Function: resolve],
      extensions: [Object]
    },
...
```
(Removed a bunch of fields for brevity.)

Also, I'm using the firestore plugin.

Let me know if there is any way to help you debug this.

**Comment by csabaxyz** [comment] 2020-04-26 15:27
After some more debugging, it looks like when the `typeComposer` has the `_gqcInputTypeComposer` property, the setup fails.

So, just to try I inserted this:
```js
delete typeComposer._gqcInputTypeComposer
```
Here:
https://github.com/gridsome/gridsome/blob/5972339e3a3de240ea76c605f92ae87369dddba5/gridsome/lib/graphql/nodes/index.js#L36

When everything works the `_gqcInputTypeComposer` property doesn't seem to exist. Maybe there is a race condition somewhere.

Also, I logged the existence of the `_gqcInputTypeComposer` outside the loop, and inside as well, and it seems like it only gets set inside the loop. There are other content types that reference the problematic type (called `Videos` in my case), so it is probable that when the other types are being set up, the Videos get affected as well, which in turn messes with the proper filter input setup at later stages.

**Comment by csabaxyz** [comment] 2020-04-26 16:40
After some more debugging, what seems to be happening here is that the references to the Videos are processed before the Videos collection itself was processed, and then when it's up to the Videos collection to set up its own filters, it thinks everything was already set up.

Based on the logs, sometimes the Videos collection is processed first and that's when everything works correctly.

So, I made a quick repro code:
```js
  api.loadSource(({ addCollection, store }) => {
    // Use the Data Store API here: https://gridsome.org/docs/data-store-api/
    const posts = addCollection({ typeName: 'Post' })
    posts.addNode({
      title: 'The post',
      author1: store.createReference('Author', '1')
    })

    const authors = addCollection({ typeName: 'Author' })
    authors.addNode({
      id: '1',
      title: 'The author'
    })
  })
```

And if the graphQL query looks like this:
```graphql
query {
  allAuthor(filter: { title: { eq: "The author" } }) {
    edges {
      node {
        id
        title
      }
    }
  }
}
```

It will return with:
```json
{
  "error": {
    "errors": [
      {
        "message": "Field \"title\" is not defined by type AuthorFilterInput.",
        "stringified": "Field \"title\" is not defined by type AuthorFilterInput.\n\nGraphQL request:2:22\n1 | {\n2 |   allAuthor(filter: {title: {eq: \"The author\"}}) {\n  |                      ^\n3 |     edges {"
      }
    ]
  }
}
```

Filtering for the `id` still works, but other fields don't.
And if you define the authors first, then it works as expected.

Hope this helps. :+1:

**Comment by hjvedvik** [comment] 2020-04-26 19:14
Thanks for all the debugging @csabaxyz :) I think the repro code in your comment should have worked, so I'll do some debugging here too and see if I can figure out what goes wrong here.

**Comment by smakinson** [comment] 2020-06-09 21:46
I am seeing a similar issue. If its helpful I had worked around it on gridsome v0.7.13, but after upgrading it no longer works.

I had worked around it previously by:

instead of: 

```
playlistsCollection.addNode({
  id: someId,
  videos: store.createReference('Videos', _.map(allPlaylistVideos, 'id')),
  ...objWithLotsoFProps
})
```

I first did: `playlistsCollection.addReference('videos', 'Videos')`

and then

```
playlistsCollection.addNode({
  id: someId,
  videos: _.map(allPlaylistVideos, 'id'),
  ...objWithLotsoFProps
})
```

Since upgrading gridsome to v0.7.15 (I skipped v0.7.14) neither way works/finds the field in the schema (VideosFilterInput)

**Comment by freshyill** [comment] 2020-06-25 21:09
I just attempted to upgrade from 0.7.12 and I'm seeing this too. Is there a fix or a workaround?

Here's an example:

```
sessions: allContent(
      filter: {
        tags: {
          contains: ["Business Meeting"]
        }
      },
      sortBy: "start",
      order: ASC
  	) {
      edges {
        node {
          title
          redirect_title
          link
          content
          description
          path
          weight
          location {
            title
          }
          date: start(format: "dddd, MMMM D, YYYY")
          start(format: "h:mm a")
          end(format: "h:mm a")
        }
      }
    }
```

**Comment by JHuppi** [comment] 2020-07-01 17:05
I encountered this same issue when upgrading from 0.7.14 to 0.7.15, but haven't found a workaround.

**Comment by hjvedvik** [comment] 2020-07-02 00:33
I think I managed to fix this issue in the referenced commit above. 

@csabaxyz The reason it failed was that the input types were created recursively in the `createFilterInput` method. So when creating an input type for `Post`, an input type for `Author` was also created because a `Post` field had a reference to it. But no fields for `Author` had been created yet. Deleting the `_gqcInputTypeComposer` property should work because it forces `Author` to create a new input type for itself. But I refactored the code to create fields for all types before any input types are created instead.

Sorry for the delay on this... I'll publish a new version tomorrow :)

**Comment by hacknug** [comment] 2020-07-02 20:37
This is great! I can confirm a regression I experienced in one of my sites is now fixed 😄

**Comment by smakinson** [comment] 2020-07-02 21:12
I believe the issue I was seeing is fixed as well. Thanks!

**Comment by hacknug** [comment] 2020-08-17 11:42
Closing this it seems the issue's been fixed. Let us know if any of you is still experiencing any issues related to this so we can re-open and look into it :+1:

**Closed by hacknug** 2020-08-17 11:42 UTC
Labels: bug

**Comment by gimyboya** [comment] 2020-12-06 01:16
@hacknug I am getting two build errors:

```bash
in ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "title" on type "Tag".

GraphQL request:18:5
17 |   tag (id: $id) {
18 |     title
   |     ^
19 |     belongsTo {
    at Object.module.exports (D:\Blogs\Stranger\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)   

 @ ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query 1:0-329 1:345-348 1:350-676 1:350-676
 @ ./src/templates/Tag.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
```

and 

```bash
in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Field "published" is not defined by type ArticleFilterInput.

GraphQL request:29:34
28 | query {
29 |   articles: allArticle(filter: { published: { eq: true }}) {
   |                                  ^
30 |     edges {
    at Object.module.exports (D:\Blogs\Stranger\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)   

 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-331 1:347-350 1:352-680 1:352-680
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
```

trying to follow [gridsome-starter-blog](https://github.com/gridsome/gridsome-starter-blog) example and got this error

I am using `gridsome 0.7.23`

any idea how I can fix this?

**Comment by jvhellemondt** [comment] 2021-01-03 19:34
It feels really strange that this fixed this issue for me.

I am using the [gridsome-starter-blog](https://github.com/gridsome/gridsome-starter-blog) and before using `@gridsome/vue-remark`, I used `@gridsome/source-filesystem`.

My old config included the following:
```
...
  templates: {
    Post: '/:title',
    Tag: '/tag/:id',
  },

  plugins: [
    {
      // Create posts from markdown files
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'Post',
        path: 'content/posts/**/*.md',
...
```

My expected config was as follows:

```
...
  templates: {
    Tag: '/tag/:id',
  },

  plugins: [
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'Post',
        baseDir: './content/posts/**/*.md',
        template: './src/templates/Post.vue',
...
```

Vue-remark uses baseDir as option instead of path. I noticed this, changed the option name and used the same string as path was. `content/posts/**/*.md',`

However, what fixed my issue was, I had to also remove the **/*.md in my baseDir option.

Final config: 
```
...
  templates: {
    Tag: '/tag/:id',
  },

  plugins: [
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'Post',
        baseDir: './content/posts',
        template: './src/templates/Post.vue',
...
```

Hope this helps someone :)
