### ISSUE TITLE
gridsome build fails with ReferenceError: window is not defined

### ISSUE THREAD

**Issue by sureshvv** [gridsome/gridsome#1124] opened 2020-04-24 06:19 UTC
When I run

`gridsome build`

I get

> 
ReferenceError: window is not defined
    at Object.<anonymous> (src/gapi_client.js:1:9)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.f322a6ac.js:68956:19)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (assets/js/app.f322a6ac.js:56344:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at assets/js/app.f322a6ac.js:118:18
    at Object.<anonymous> (assets/js/app.f322a6ac.js:121:10)
    at o (/home/s/somegrid/node_modules/vue-server-renderer/build.prod.js:1:77607)
    at /home/s/somegrid/node_modules/vue-server-renderer/build.prod.js:1:78200
`

my `main.js` has `import './gapi_client'` at the very top.

My env:

>

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (2) x64 AMD A6-4400M APU with Radeon(tm) HD Graphics
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
  npmPackages:
    gridsome: ^0.7.14 => 0.7.14 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

Some questions:

1. Why is gapi_client.js referencing window?

2. Should gapi_client.js be imported only when process.isClient is true?

3. I changed the code in `main.js` as follows:

>

  if (process.isClient) {
       window.gapi_client = require('./gapi_client')
  } 

4. Now my build seems to go thru that step but fails with

>

Error: No native build was found for runtime=node abi=67 platform=linuxglibc arch=x64
    at Function.module.exports.load.path (node_modules/node-gyp-build/index.js:56:0)
    at load (node_modules/node-gyp-build/index.js:18:0)
    at Object.<anonymous> (node_modules/leveldown/binding.js:1:41)
    at Object.<anonymous> (assets/js/app.ce34d4e7.js:28227:30)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (node_modules/leveldown/leveldown.js:3:16)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (node_modules/level/level.js:1:43)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (assets/js/app.ce34d4e7.js:9411:13)

>

**Comment by Edmund1645** [comment] 2020-04-25 15:38
Could you please a public replication of the repo?

**Comment by sanscheese** [comment] 2020-04-27 22:55
Duplicate of #800

In response to your questions:
1. you can see `window` used in its code.  https://github.com/kevinschaich/gapi-client/blob/master/index.js
As its a client-side library it will make sense for it to access the `window` object.

2. Yes. Also, ensure when you then only use the gapi_client library elsewhere in your code on the `client`

3/4. This is tricky without seeing your codebase. If you have a public repo, it will be easier for others to help.

**Closed** 2020-04-28 09:25 UTC
