### ISSUE TITLE
actions.getCollection always returns undefined in plugin

### ISSUE THREAD

**Issue by mklueh** [gridsome/gridsome#1342] opened 2020-09-13 08:35 UTC
## Description

I need to iterate through a collection after it is created and modify some nodes based on information of other nodes.

My idea was to use actions.getCollection()

```
    api.loadSource(async actions => {
      console.info(actions.getCollection("posts"));
      console.info(actions.getCollection("Posts"));
      console.info(actions.getCollection("post"));
      console.info(actions.getCollection("Post"));
    });
```

However, there is never a collection returned and I get undefined instead on all calls.

It´s not clear to me what is wrong with that code, because I´m just following the docs, but I´m assuming the callback is executed before the collections are created.

Appreciate any hints and tips on how to get collections after they are created to be able to modify them before the pages are created.

**Comment by noxify** [comment] 2020-09-13 09:41
> modify some nodes based on information of other nodes

Is `onCreateNode` not better for this? 
--> https://gridsome.org/docs/server-api/#apioncreatenodefn

Anyway.. i have tested it with `source-filesystem` and it seems to work.

```js
//gridsome.config.js
module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'BlogPost',
        path: './content/*.md',
      }
    }
  ]
}
```

I got a response with and without `async`

```
  api.loadSource(actions => {
    console.log(actions.getCollection('BlogPost'));
  })

    api.loadSource(async actions => {
    console.log(actions.getCollection('BlogPost'));
  })
```

Result is something like this:

```
Initializing plugins...
Collection {
  typeName: 'BlogPost',
  options: {
    typeName: 'BlogPost',
    route: undefined,
    resolveAbsolutePaths: false,
    _indices: [ 'path' ],
    _unique: [ 'path' ]
  },
  //...
```

----

I assume you're using a remote source - it's possible that the collection doesn't exists at the moment.
We had this problem in the past with the image downloader plugin.
We solved the problem with the remote sources after moving the logic into the `onBootstrap`.

**Comment by mklueh** [comment] 2020-09-13 11:44
@noxify Thanks for the fast response.

I´m using the **source-filesystem** as well as my only file source besides https://gridsome.org/plugins/gridsome-source-static-meta (which is not what I´m trying to access). No remote source.

Sync and async produce the same result, however I´ve now tried to fetch the collection once in my plugin I´m trying to develop and once in the application itself:

Logs:
```
collection (plugin) undefined
collection (application) Collection {
  typeName: 'Post',
  options: {
    typeName: 'Post',
    route: undefined,
    resolveAbsolutePaths: false,
    _indices: [ 'path' ],
    _unique: [ 'path' ]
  },

```

**It works as expected in the application (or actual site) but not in the plugin project.**

This is all I´m doing in my **gridsome-server.js** of the plugin

```
module.exports = function (api) {
    api.loadSource(actions => {
        console.log("collection (plugin)",actions.getCollection("Post"));
    })
}

```

Which is included in my project using **yarn link**


Thanks, I´ll look into onCreateNode

**Comment by noxify** [comment] 2020-09-13 13:38
> Do you think it´s the right hook if you need to build relations between nodes?

This depends of what you want to do :)

We use the `onCreateNode` currently in some basic use cases ( e.g. transforming the `tags` inside a blog post )
In this cases we have the relation defined in the source definition ( BlogPost --> Tag ).

> It works as expected in the application (or actual site) but not in the plugin project.

I will give it a try, to see if I can reproduce your problem.

**Comment by noxify** [comment] 2020-09-13 14:01
Ok...

created shortly a local package with the following contents:
( files are stored inside the gridsome project in `packages/gridsome-test-plugin` )

```
// packages/gridsome-test-plugin/package.json
{
  "name": "gridsome-test-plugin",
  "version": "1.0.0",
  "main": "gridsome.server.js",
  "license": "MIT",
  "private": true
}

```

```
// packages/gridsome-test-plugin/gridsome.server.js
module.exports = function (api) {
    api.loadSource(async actions => {
        console.log(actions.getCollection('BlogPost'));
    })
}
```

Then I ran `yarn install` inside the package directory.
After installing, I have ran `yarn link`.

Moved to the gridsome project root and ran `yarn link gridsome-test-plugin`.

Inside the `gridsome.config.js`, I have the following config:

```
// gridsome.config.js

module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'BlogPost',
        path: './content/*.md',
      }
    },
    {
      use: 'gridsome-test-plugin'
    }
  ]
}

```

I have currently only one `md` file inside the `content` directory - but after calling `gridsome develop` I was able to see the `console.log` with the collection.

**BUT**, if I use the following plugin config inside the `gridsome.config.js`, I was able to reproduce your problem:

```
plugins: [
    {
      use: 'gridsome-test-plugin'
    },
    {
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'BlogPost',
        path: './content/*.md',
      }
    }
  ],
```

I would make sure, that your plugin is loaded after your source definition and if this doesn't solve your problem, you should better use `onCreateNode` or `onBootstrap`.

**Comment by mklueh** [comment] 2020-09-13 14:08
@noxify Oh dear, you are right. I didn´t know the plugin order matters. 

Is this behaviour intentional or just a side effect?

**Comment by noxify** [comment] 2020-09-13 14:14
> I didn´t know the plugin order matters.

I have checked the code and there is no "load order" or something implemented.
Everything will be called via `Promise`.
If you have a remote source, the `console.log` is shown, before the remote source is done.

**Question: ** Does this solve your problem for now?

**Comment by mklueh** [comment] 2020-09-13 19:02
@noxify I´ve added a hint to the readme for now and an example where the source-filesystem plugin is above mine https://github.com/mklueh/gridsome-plugin-recommender

Thank you very much for your help

**Comment by noxify** [comment] 2020-09-13 20:00
You're welcome :)

BTW. Will check if I can integrate your plugin into our starters and replace the Tag based related posts.

I will close this issue since we solved the problem :)

**Closed** 2020-09-13 20:02 UTC
Labels: question
