### ISSUE TITLE
Markdown file title not support Chinese?

### ISSUE THREAD

**Issue by chenhongen** [gridsome/gridsome#956] opened 2020-01-27 07:42 UTC
## Description

(node:6268) UnhandledPromiseRejectionWarning: TypeError: Expected "title" to be a string

### Steps to reproduce

When set title with Chinese in markdown file,It show the error.

### Expected result

Support Chinese

### Actual result

![image](https://user-images.githubusercontent.com/16499303/73157312-905a9780-411b-11ea-935c-6c5f112447fc.png)

### Environment

gridsome: 0.7.12

**Comment by tangyiming** [comment] 2020-02-02 01:05
you can change the gridsome config. 
Add a custom path rather than use route.
```
// This is where project configuration and plugin options are located. 
// Learn more: https://gridsome.org/docs/config

// Changes here requires a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`

module.exports = {
  siteName: 'blog by Eamon',
  siteDescription: 'While the world sleep I dream',
  siteUrl: 'https://tangyiming.github.io',
  plugins: [
    {
      // Create posts from markdown files
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'Post',
        path: 'content/posts/*.md',
        // route: '/:slug',
        refs: {
          // Creates a GraphQL collection from 'tags' in front-matter and adds a reference.
          tags: {
            typeName: 'Tag',
            route: '/tag/:id',
            create: true
          }
        }
      }
    }
  ],

  transformers: {
    //Add markdown support to all file-system sources
    remark: {
      externalLinksTarget: '_blank',
      externalLinksRel: ['nofollow', 'noopener', 'noreferrer'],
      anchorClassName: 'icon icon-link',
      plugins: [
        '@gridsome/remark-prismjs'
      ]
    }
  },
}
```

**Comment by zacnomore** [comment] 2020-02-13 16:26
Closing as a duplicate of #918, the test cases in that one are very thorough!
I'm going to link to your workaround @tangyiming in there as well

**Closed by zacnomore** 2020-02-13 16:26 UTC

**Comment by chenhongen** [comment] 2020-02-25 14:43
I tried your method, although it made it complicated, it didn't give me error again.By the way,Do you know how to make `gridsome-plugin-flexsearch` to surpport Chinese?

**Comment by kongmoumou** [comment] 2020-03-29 15:32
Currently my solution is to set `path` option as a function in the `templates` config.

This is my `gridsome.config.js`

```js
module.exports = {
  ...
  templates: {
    Post: [
      {
        path: (node) => {
          const postPathPrefix = /^\/content\/posts/;
          return node.path.replace(postPathPrefix, '');
        }
      },
    ],
    Tag: '/tag/:id'
  },
  ...
}
```

But I still hope it can customize the path in `md` file's `frontmatter` just like [Gatsby](https://www.gatsbyjs.org/docs/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files)

**Comment by chenhongen** [comment] 2020-03-30 05:08
Reffer to [gridsome-plugin-flexsearch](https://github.com/thetre97/gridsome-plugin-flexsearch/issues/23#event-3172979300)

**Comment by ceynri** [comment] 2021-05-10 09:56
Use `:fileInfo__name` instead of `:title` in `gridsome.config.js` route config if your filename is legal. It will use the filename as the url path.

example:
```js
// gridsome.config.js

module.exports = {
  // ...
  templates: {
    Post: '/:fileInfo__name',  // default: Post: '/:title'
    Tag: '/tag/:id',
  },
  // ...
}
```

This method comes from [#17](https://github.com/gridsome/gridsome/issues/17#issuecomment-478746477)
