### ISSUE TITLE
@gridsome/source-filesystem and @gridsome/transform-remark show tags one way, but not the other.

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [gridsome/gridsome#1005] opened 2020-02-22 22:38 UTC
## Description

Having followed the taxonomy page instructions in the docs and created a taxonomy page with tags that are stored as a YAML array in the Markdown file, the tags show up on the post, but when you go to the taxonomy page, the page is blank (and so is the GraphQL query). To make it work, you need to delete or add one tag from the array. Then, the taxonomy page updates effortlessly.

### Steps to reproduce

1. [Clone this repo.](https://github.com/zbigniewzolnierowicz/blogfolio)
2. Run `gridsome develop`
3. In the GraphQL Explorer run the following queries:
```graphql
query {
  allBlogPost {
    edges {
      node {
        id
        tags {
          id
        }
      }
    }
  }
}
```
```graphql
query {
  allTag {
    totalCount
  	edges {
      node {
        id
        belongsTo {
          edges {
            node {
              ... on BlogPost {
                id
              }
            }
          }
        }
      }
    }
  }
}
```
The results should be:
```json
{
  "data": {
    "allBlogPost": {
      "edges": [
        {
          "node": {
            "id": "7d6eb3a9b747794d5abccc193900350f",
            "tags": [
              {
                "id": "story"
              },
              {
                "id": "creative"
              }
            ]
          }
        }
      ]
    }
  }
}
```
```json
{
  "data": {
    "allTag": {
      "totalCount": 2,
      "edges": [
        {
          "node": {
            "id": "creative",
            "belongsTo": {
              "edges": []
            }
          }
        },
        {
          "node": {
            "id": "story",
            "belongsTo": {
              "edges": []
            }
          }
        }
      ]
    }
  }
}
```
4. Go to `/content/blog/run-runaway.md`
5. Change
```yaml
tags:
    - "story"
    - "creative"
```
to
```yaml
tags:
    - "story"
```
then again to
```yaml
tags:
    - "story"
    - "creative"
```

### Expected result

The results of the two initial queries should become
```json
{
  "data": {
    "allBlogPost": {
      "edges": [
        {
          "node": {
            "id": "7d6eb3a9b747794d5abccc193900350f",
            "tags": [
              {
                "id": "story"
              },
              {
                "id": "creative"
              }
            ]
          }
        }
      ]
    }
  }
}
```
and
```json
{
  "data": {
    "allTag": {
      "totalCount": 2,
      "edges": [
        {
          "node": {
            "id": "creative",
            "belongsTo": {
              "edges": [
                {
                  "node": {
                    "id": "7d6eb3a9b747794d5abccc193900350f"
                  }
                }
              ]
            }
          }
        },
        {
          "node": {
            "id": "story",
            "belongsTo": {
              "edges": [
                {
                  "node": {
                    "id": "7d6eb3a9b747794d5abccc193900350f"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

### Actual result

Cannot change files during the build process, thus rendering the "fix" outlined in the steps to reproduce moot.

### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 13.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12
    gridsome-plugin-remark-youtube: ^1.0.1 => 1.0.1
```

**Comment by noxify** [comment] 2020-02-24 09:43
Hi @zbigniewzolnierowicz,

it seems you have moved to `gatsby` and we can't reproduce the issue.

I will close the issue for now - If there are any questions (gridsome related ;) ) feel free to re-open the issue or create a new one.

Thanks!

**Closed by noxify** 2020-02-24 09:43 UTC

**Comment by zbigniewzolnierowicz** [comment] 2020-02-24 14:42
Whoops! Sorry, here's the [backup repository](https://github.com/zbigniewzolnierowicz/blogfolio-backup) with all the code.
