### ISSUE TITLE
JS-imported style output is repeated in the <head> of built pages; breaks layouts

### ISSUE THREAD

**Issue by courcelan** [gridsome/gridsome#163] opened 2019-01-31 07:43 UTC
## Description

When using `gridsome build`, I get repeated `<link>`s to my styles that are imported in `main.js` The repeated `<link>` then overwrites (due to css specificity) component-based styles. These link files are also repeated in the `preload` section. Because of the redeclaration of the `<link>` my styles are "failing" on completion of `gridsome build`

### Steps to reproduce

in main.js, I import:

```javascript
import vefa from "@/themes/vefa/vefa.styl"
import app from "@/themes/v1/app.styl"
```

after completion of `gridsome build`, pages have this:
```html
1  | <link rel="preload" href="/assets/css/styles.f5f205b3.css" as="style">
2  | <link rel="preload" href="/assets/js/app.82a76764.js" as="script">
3  | <link rel="preload" href="/assets/css/component--admin-news.styles.bd45ac71.css" as="style">
4  | <link rel="preload" href="/assets/js/component--admin-news.f26ddc0d.js" as="script">
5  | <link rel="preload" href="/assets/js/component--admin~component--admin-events~component-- admin-members~component--admin-news~component--a~643eda85.f26e2d87.js" as="script">
6  | <link rel="preload" href="/assets/css/styles.f5f205b3.css" as="style">
7  | <link rel="prefetch" href="/assets/js/component--accounts-request-password-reset.8fe843ac.js">
8  | <link rel="prefetch" href="/assets/js/component--accounts.4c2fb2ee.js">
9  | <link rel="prefetch" href="/assets/js/component--accounts~component--accounts-request-password-reset~component--admin~component--admin-eve~76ed8478.f7b36fbd.js">
10 | <link rel="prefetch" href="/assets/js/component--accounts~component--log-in~component--log-out.9409463a.js">
11 | <link rel="prefetch" href="/assets/js/component--admin-events.b5d0980e.js">
12 | <link rel="prefetch" href="/assets/js/component--admin-members.182e2eb4.js">
13 | <link rel="prefetch" href="/assets/js/component--admin-members~component--admin-news~component--admin-users~component--contact~component--~df896b38.84d6a1ce.js">
14 | <link rel="prefetch" href="/assets/js/component--admin-news~component--dashboard-news.a90b85a8.js">
15 | <link rel="prefetch" href="/assets/js/component--admin-users.f589ab95.js">
16 | <link rel="prefetch" href="/assets/js/component--admin.7882306f.js">
17 | <link rel="prefetch" href="/assets/js/component--contact-thank-you.4c63474b.js">
18 | <link rel="prefetch" href="/assets/js/component--contact.04b7109e.js">
19 | <link rel="prefetch" href="/assets/js/component--dashboard-documents-uploaded.aff93024.js">
20 | <link rel="prefetch" href="/assets/js/component--dashboard-documents.9ab193d3.js">
21 | <link rel="prefetch" href="/assets/js/component--dashboard-events.c18aa2a0.js">
22 | <link rel="prefetch" href="/assets/js/component--dashboard-news.68bdb9f8.js">
23 | <link rel="prefetch" href="/assets/js/component--dashboard.f8a28dce.js">
24 | <link rel="prefetch" href="/assets/js/component--dashboard~component--dashboard-documents~component--dashboard-documents-uploaded~componen~b5ac6ddd.b6494891.js">
25 | <link rel="prefetch" href="/assets/js/component--home.21b72216.js">
26 | <link rel="prefetch" href="/assets/js/component--log-in.cdc0c2ee.js">
27 | <link rel="prefetch" href="/assets/js/component--log-in~component--log-out.f86487f9.js">
28 | <link rel="prefetch" href="/assets/js/component--log-out.d4da3839.js">
29 | <link rel="prefetch" href="/assets/js/page-query.623966ba.js">
30 | <link rel="prefetch" href="/assets/js/vendors~component--admin-members~component--admin-news~component--admin-users~component--dashboard-d~600775d8.cc1a6d2f.js">
31 | <link rel="prefetch" href="/assets/js/vendors~component--admin-news~component--dashboard-documents~component--dashboard-documents-uploaded~71b353a0.2fa27b16.js">
32 | <link rel="stylesheet" href="/assets/css/styles.f5f205b3.css">
33 | <link rel="stylesheet" href="/assets/css/component--admin-news.styles.bd45ac71.css">
34 | <link rel="stylesheet" href="/assets/css/styles.f5f205b3.css">
```

You can see that lines 1 and 6 are repeated and lines 32 and 34 as well.

### Expected result

I expect to see the css layouts on my static site when the site is in the same state as `gridsome develop`'s HMR

### Actual result

Styles are not the same, they are overwritten, and there are extra elements and link calls in the `<head>`

**Comment by courcelan** [comment] 2019-01-31 07:50
Also, imported style files should appear before component style files, so I'd expect the `<link>` at line 34 to not be there.

**Comment by probil** [comment] 2019-10-23 19:24
I can't reproduce with latest gridsome. 

I have an empty project with `stylus` and `stylus-loader`.
Two stylus files (with some css) are imported into `main.js`. I also have styles in components.

Entire `<head>` of the `gridsome build`:
```html
<head>
  <title>Hello, world! - Gridsome</title>
  <meta name="gridsome:hash" content="4a00a15ea6b65ca3bd719cad55d9d354c158f48e">
  <meta data-vue-tag="ssr" charset="utf-8">
  <meta data-vue-tag="ssr" name="generator" content="Gridsome v0.7.8">
  <meta data-vue-tag="ssr" data-key="viewport" name="viewport"
        content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta data-vue-tag="ssr" data-key="format-detection" name="format-detection" content="telephone=no">
  <link data-vue-tag="ssr" rel="icon" href="data:,">
  <link data-vue-tag="ssr" rel="icon" type="image/png" sizes="16x16" href="/assets/static/favicon.ce0531f.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="icon" type="image/png" sizes="32x32" href="/assets/static/favicon.ac8d93a.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="icon" type="image/png" sizes="96x96" href="/assets/static/favicon.b9532cc.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="apple-touch-icon" type="image/png" sizes="76x76"
        href="/assets/static/favicon.f22e9f3.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="apple-touch-icon" type="image/png" sizes="152x152"
        href="/assets/static/favicon.62d22cb.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="apple-touch-icon" type="image/png" sizes="120x120"
        href="/assets/static/favicon.1539b60.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="apple-touch-icon" type="image/png" sizes="167x167"
        href="/assets/static/favicon.dc0cdc5.9bb7ffa.png">
  <link data-vue-tag="ssr" rel="apple-touch-icon" type="image/png" sizes="180x180"
        href="/assets/static/favicon.7b22250.9bb7ffa.png">
  <noscript data-vue-tag="ssr">
    <style>.g-image--loading {
      display: none;
    }</style>
  </noscript>
  <link rel="preload" href="/assets/css/0.styles.714679c3.css" as="style">
  <link rel="preload" href="/assets/js/app.a12203ee.js" as="script">
  <link rel="preload" href="/assets/js/page--src--pages--index-vue.c90ac913.js" as="script">
  <link rel="prefetch" href="/assets/js/page--node-modules--gridsome--app--pages--404-vue.bcf389fb.js">
  <link rel="prefetch" href="/assets/js/page--src--pages--about-vue.0f35f5ae.js">
  <link rel="stylesheet" href="/assets/css/0.styles.714679c3.css">
</head>
```
As you can see there is no duplication. @courcelan can you please confirm that it's fixed in latest version? 

I think it was fixed automatically or the issue author was using some kind of plugin (post-css, etc) with a bug

```
Gridsome: v0.7.8
OS: Archilinux (Antergos)
CLI: v0.3.1
```

**Comment by courcelan** [comment] 2019-10-23 19:29
@probil I have not had an issue for a while! this was fixed in .0.4.7 per gridsome changelog https://github.com/gridsome/gridsome/blob/master/gridsome/CHANGELOG.md#047-2019-02-04

**Closed** 2019-10-23 19:29 UTC
Labels: bug
