### ISSUE TITLE
GraphQL source plugin: Schema must contain uniquely named types but contains multiple types named "Mutation".

### ISSUE THREAD

**Issue by brpaz** [gridsome/gridsome#967] opened 2020-02-02 10:46 UTC
## Description

I am using the grahpql source plugin with GitHub API and get the following error when running `gridsome develop`

```
Error: Schema must contain uniquely named types but contains multiple types named "Mutation".
    at typeMapReducer (/home/bruno/Code/Personal/sites/brunopaz.dev/node_modules/graphql/type/schema.js:262:13)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/bruno/Code/Personal/sites/brunopaz.dev/node_modules/graphql/type/schema.js:145:28)
    at SchemaComposer.buildSchema (/home/bruno/Code/Personal/sites/brunopaz.dev/node_modules/graphql-compose/lib/SchemaComposer.js:133:12)
    at Schema.buildSchema (/home/bruno/Code/Personal/sites/brunopaz.dev/node_modules/gridsome/lib/app/Schema.js:35:35)
    at Plugins.createSchema (/home/bruno/Code/Personal/sites/brunopaz.dev/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I think this issue might not be directly related with Gridsome, but still, didnt know where to put it.
An update to the latest `graphql-js` seems to solve it but breaks on next on other things.

### Steps to reproduce

Just add the graphql-source-plugin with GitHub API

```
 {
      use: 'gridsome-source-graphql',
      options: {
        url: 'https://api.github.com/graphql',
        fieldName: 'github',
        typeName: 'githubRepos',

        headers: {
          Authorization: `Bearer ${process.env.GITHUB_TOKEN}`
        }
      }
    },
```

### Expected result

The GraphQL schema should be imported successfully.

### Actual result

An error occurred

### Environment

```
 System:
    OS: Linux 5.3 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0 
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
    @gridsome/vue-remark: ^0.1.9 => 0.1.9 
    gridsome: ^0.7.12 => 0.7.12 
    gridsome-plugin-modal: brpaz/gridsome-plugin-modal#add-modal-options => 0.1.1 
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9 
    gridsome-plugin-remark-shiki: ^0.3.1 => 0.3.1 
    gridsome-plugin-rss: ^1.2.0 => 1.2.0 
    gridsome-plugin-sentry: ^1.1.0 => 1.1.0 
    gridsome-source-graphql: ^1.0.2 => 1.0.2 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by narration-sd** [comment] 2020-02-05 01:08
I'm getting and chasing this also, where I don't think I did before. The schema contains different but related objects with same-name contents:  PageInfo, the usual thing for pageable Connections.

You say the problem goes away on 'latest' graphql-js.  Do you mean one of the RC 15.0 versions? Which I think are known not ready for prime time, have conflicts with using packages.

I'm on latest released, 14.6, and thinking of backing up some versions to see if this problem isn't recently introduced.

**Comment by narration-sd** [comment] 2020-02-07 00:50
Ok, I think I've run this down, and have proved an apparent fix: 

I've raised this in a fresh issue at github for graphql-js:  https://github.com/graphql/graphql-js/issues/2439

Before they react, if needing to get a project back on the air, you can apply the fix directly in the compiled version of graphql/type/schema.js within your project's node_modules, at line 261 for version 14.6, the present release. It works the same on 15.0.0-rc.1, where it's at line 314.  

You can't use 15 unless you forceably remove the extra copy of graphql which appears within gridsome's node_module. I don't think it's used for anything except possibly during production of the module, which we aren't doing when we use it. 

I tried the fix out with graphql-js 15 just to be sure about it, and asked them to produce it in a new version of 14 so we can use it before they get 15 completed.

**Comment by narration-sd** [comment] 2020-02-07 06:33
...and, @IvanGoncharov who handles graphql-js has come right back, and indicated my later thoughts that the test as written was intentional were correct. So the above 'solution' is indeed a workaround, which may possibly work for you also, perhaps only as long as you're not actually using PageInfo or Mutations, which seems likely in the Gridsome area.

You can find my notes below his at https://github.com/graphql/graphql-js/issues/2439#issuecomment-583214745, and I guess I will need to take this up with the Gridsome brothers as it looks like they wrote the source-graphql plugin themselves, which seems to be where the issue may be occuring, as discussed in those notes.

**Comment by narration-sd** [comment] 2020-02-07 07:05
@hjvedvik Hans-Jørgen, maybe I could ask you to look in on this?

As above, I've already gone over it  with @IvanGoncharov at graphql-js, and from the notes you can find beginning here: https://github.com/graphql/graphql-js/issues/2439#issuecomment-583214745, you can see that the problem appears to be coming in the graphql-source plugin, I suspect around the application of libraries to handle the typeName prefixes.

That comment also holds some zips with relevant logs, I think showing that the original GraphQL server is sending a reasonable schema, and where the results fall a little apart. So seems best to link, than replicate all that over here.

If you'll let me know an apropos email, I'll send you the server graphql API point for this, with the Bearer token for Authorization, so you can have a look or make tests yourself.

I haven't forgotten we began an interesting conversation over Live Vue -- you know the ship needs occasional steering, and that's what's been going on here, all the while watching it work with Gridsome.

Tusen takk,
Clive

**Comment by narration-sd** [comment] 2020-02-08 03:57
Ok, I've gotten to the bottom of this here, and because of getting a rather inside look at how schema stitching of multiple GraphQL sources actually works, I think the system is sound.

@brpaz  Bruno, I am imagining you have a similar situation, and so will be able now to get your project repaired and thus close this issue.

What I found in the end is that I had an extra configuration, left over I believe from early days using another external source plugin. This code was in gridsome.server.js. It added a schema built from the same server as I'm using for the later source-graphql, which set up in gridsome.config.js.

This extra schema was quite valid, on printing it out, but had two crucial problems: a) it essentially duplicated the schema properly loaded by source-graphql, and b) it didn't have the proper `typeName` prefixing, while the more visible one from the source-graphql plugin did, which hid the issue for a while. 

Without the prefixes, the raw PageInfo and Mutation terms in this extra schema collide with those from Gridsome's primary source. This is the reason for the errors, which the validator in `graphql-js` properly reported and halted on.

Simply removing the outdated code from gridsome.server.js, and thus eliminating this improper source, brought the Gridsome project back to building and operating very nicely, as it always has.

What worked for troubleshooting this was a combination of logging points across various schema builders, very importantly markered for sequence by a set of stack traces nicely suggested by @IvanGoncherov. It's not a low-effort proposition, but did gain me that insight on how the schema-stitcihing of multiple data sources works out.

Both graphql-js and Grisome prove out to be solid in this rather hidden area, and so good confidence comes in each of them, and how well they work together.

**Comment by stereokai** [comment] 2020-07-20 00:06
Getting this as well, same setup, different DB, any clues?

**Comment by stereokai** [comment] 2020-07-20 14:33
@TerabyteTiger 

## Description
```console
Gridsome v0.7.19

Initializing plugins...
Load sources - 0s
Error: Schema must contain uniquely named types but contains multiple types named "Mutation".
    at typeMapReducer (project/node_modules/.pnpm/graphql@14.7.0/node_modules/graphql/type/schema.js:262:13)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (project/node_modules/.pnpm/graphql@14.7.0/node_modules/graphql/type/schema.js:145:28)
    at SchemaComposer.buildSchema (project/node_modules/.pnpm/graphql-compose@7.18.1_graphql@14.7.0/node_modules/graphql-compose/lib/SchemaComposer.js:153:12)
    at Schema.buildSchema (project/node_modules/.pnpm/gridsome@0.7.19/node_modules/gridsome/lib/app/Schema.js:35:35)
    at Plugins.createSchema (project/node_modules/.pnpm/gridsome@0.7.19/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
### Steps to reproduce
In `gridsome.config.js`:
```js
module.exports = {
  plugins: [
    {
      use: 'gridsome-source-graphql',
      options: {
        url: 'http://localhost:8888/graphql',
        fieldName: 'gqlFieldName',
        typeName: 'gqlTypeName',
      },
    },
  ],
}
```
`url` is pointing to a local GraphQL server (verified to be working correctly and consumable)

### Expected result

Gridsome should consume the GraphQL properly and load the app

### Actual result

Gridsome throws the error above and exits, does not start app

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.19
    gridsome-source-graphql: ~1.0.2 => 1.0.2
```

**Comment by djmtype** [comment] 2020-07-25 22:55
Getting this same error with Onegraph. Any resolution?

```
module.exports = {
  plugins: [
    {
      use: 'gridsome-source-graphql',
      options: {
        url: 'https://serve.onegraph.com/graphql?app_id=abc-6b30-456d-8b8b-xxxx,
        fieldName: 'oneGraph',
        typeName: 'ONEGRAPH'
      },
    },
  ],
}
```

**Comment by stereokai** [comment] 2020-07-27 13:06
@djmtype I ended up removing all the package locks (yarn, npm, pnpm) and do a fresh reinstall using yarn with these dependencies:
```json
    "@gridsome/source-graphql": "~0.1.0",
    "graphql": "^14.0.0",
    "gridsome": "^0.7.0",
```

**Comment by djmtype** [comment] 2020-07-27 13:19
@stereokai There was a thread I followed which modified some of the plugin's code which worked out for me as well, but your recommendation is obviously better.

For my case, I ended up using the official Gridsome GraphQL plugin as it suited my project's needs since I didn't need mutations.

**Comment by stereokai** [comment] 2020-07-27 13:23
I wasn't aware `source-graphql` doesn't support mutations. I'm also just learning the ropes here :)

**Closed** 2021-12-12 16:23 UTC
