### ISSUE TITLE
Dependency not found error can be misleading

### ISSUE THREAD

**Issue by renestalder** [gridsome/gridsome#73] opened 2018-12-14 16:45 UTC
## Description

If you're referencing own, internal dependencies (not node_modules) that do not exist, Gridsome answers with:

```
This dependency was not found:

* ~/layouts/Default.vue in ./src/main.js

To install it, you can run: npm install --save ~/layouts/Default.vue
```

I'm not sure if this comes from Webpack or Gridsome. But I work quite some years with Webpack and never got the suggestion to install something via npm the way Gridsome does.

### Steps to reproduce

Import a file or asset that doesn't exist.

### Expected result

Error about missing dependency, but no note about installing dependencies when using Webpack's tilde to reference.

### Actual result

Tells me to install dependencies via npm which would not work of course.

**Comment by hjvedvik** [comment] 2019-04-01 21:32
The message comes from `friendly-errors-webpack-plugin` and it looks like it only checks for `./`and `../` to determine if it's a module or package, so an alias like `~` is treated as a package. I'm not sure what we can do about it.

**Comment by robaxelsen** [comment] 2019-04-07 15:44
Closing this, as issue is caused by webpack plugin and not Gridsome.

**Closed by robaxelsen** 2019-04-07 15:44 UTC

**Comment by jimfilippou** [comment] 2019-12-08 21:26
Any work around? Closing issues without referencing anything is not smart..
