### ISSUE TITLE
gridsome create site-name pngquant pre-build test failed

### ISSUE THREAD

**Issue by olofhultberg** [gridsome/gridsome#378] opened 2019-04-23 12:11 UTC
## Description

```unable to get local issuer certificate
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng is installed
    at Promise.all.then.arr (/Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/execa/index.js:231:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/olof.hultberg/.npm/_logs/2019-04-23T11_46_19_702Z-debug.log
```

### Steps to reproduce

1. Yarn global add @gridsome/cli (works fine)
2. gridsome create my-site-name (fails)

### Expected result

All dependencies should install just fine and the gridsome develop command should fire up a new gridsome site on http://localhost:8080

### Actual result

```Clone https://github.com/gridsome/gridsome-starter-default.git 1.63s
❯ Update project package.json 0.02s
❯ Install dependencies
  • Building fresh packages (4 of 4)
Error: Failed to install dependencies with yarn. Please enter vue-static directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.child.on.code (/Users/olof.hultberg/.config/yarn/global/node_modules/@gridsome/cli/lib/commands/create.js:100:17)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

### Environment

<pre><code>
Libs:
- gridsome version: X.Y.Z
- @gridsome/cli version: X.Y.Z

Browser:
- [ X] Chrome (desktop)version 73.0.3683.103 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v11.11.0
- Platform:  MacOS Mojave (10.14.4)

Others:
I have tested to run yarn install afterwards to add all the depencies but it fails.

If i run the gridsome develop command I get this:
```
  Site running at:          http://localhost:8081/
  Explore GraphQL data at:  http://localhost:8081/___explore

Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Error: spawn /Users/olof.hultberg/dev/repo/leveluptuts-gridsome/vue-static/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
````
http://localhost/8080 looks like this:

![Screenshot 2019-04-23 at 14 10 36](https://user-images.githubusercontent.com/39264339/56579890-98583a80-65d1-11e9-94a5-6968e0326c53.png)

</code></pre>

**Comment by uossareisser** [comment] 2019-05-05 13:35
**Gatsby and Gridsome pngquant-bin**

**1. Gatsby error**

C:\>gatsby new gatsby-site-03 https://github.com/gatsbyjs/gatsby-starter-blog && cd gatsby-site-03
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-blog.git
Cloning into 'gatsby-site-03'...
remote: Enumerating objects: 1987, done.
remote: Total 1987 (delta 0), reused 0 (delta 0), pack-reused 1987
Receiving objects: 100% (1987/1987), 5.36 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (1170/1170), done.
success Created starter directory layout
info Installing packages...
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ? waiting...
[2/5] ? sharp
[3/5] ? mozjpeg
[4/5] ? pngquant-bin
error C:\gatsby-site-03\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\gatsby-site-03\node_modules\pngquant-bin
Output:
!! Command failed: C:\gatsby-site-03\node_modules\pngquant-bin\vendor\pngquant.exe --version

 !! pngquant pre-build test failed
  i compiling from source

error Command failed: yarnpkg

  Error: Command failed: yarnpkg

  - index.js:236 Promise.all.then.arr
    [npm]/[gatsby-cli]/[execa]/index.js:236:11

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

**2. Gridsome error**

C:\gridsome-site-03>npm install @gridsome/cli
npm WARN rm not removing C:\gridsome-site-03\node_modules\.bin\gridsome.cmd as it wasn't installed by C:\gridsome-site-03\node_modules\@gridsome\cli
npm WARN rm not removing C:\gridsome-site-03\node_modules\.bin\gridsome as it wasn't installed by C:\gridsome-site-03\node_modules\@gridsome\cli
npm WARN rm not removing C:\gridsome-site-03\node_modules\.bin\json5.cmd as it wasn't installed by C:\gridsome-site-03\node_modules\json5
npm WARN rm not removing C:\gridsome-site-03\node_modules\.bin\json5 as it wasn't installed by C:\gridsome-site-03\node_modules\json5

> sharp@0.21.3 install C:\gridsome-site-03\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\Nathalie\AppData\Roaming\npm-cache\_libvips\libvips-8.7.0-win32-x64.tar.gz
info sharp Creating C:\gridsome-site-03\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\gridsome-site-03\node_modules\sharp\vendor\lib to C:\gridsome-site-03\node_modules\sharp\build\Release

> cwebp-bin@5.0.0 postinstall C:\gridsome-site-03\node_modules\cwebp-bin
> node lib/install.js

  v cwebp pre-build test passed successfully

> mozjpeg@6.0.1 postinstall C:\gridsome-site-03\node_modules\mozjpeg
> node lib/install.js

  v mozjpeg pre-build test passed successfully

> pngquant-bin@5.0.2 postinstall C:\gridsome-site-03\node_modules\pngquant-bin
> node lib/install.js

  !! Command failed: C:\gridsome-site-03\node_modules\pngquant-bin\vendor\pngquant.exe --version


  !! pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (C:\gridsome-site-03\node_modules\bin-build\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathalie\AppData\Roaming\npm-cache\_logs\2019-05-05T13_21_59_017Z-debug.log

**3. Environment**

Libs:

- @gridsome/cli version: 0.0.9
- gridsome v0.5.8
- @gastby/cli 2.5.12
- gatsby: 2.5.12

For Tooling issues:
- Node version: v10.15.3
- Platform:  Windows 10

**Comment by krstic-duci** [comment] 2019-05-11 12:57
Hello @olofhultberg since you are using MacOS Mojave, did you tried to install the **libpng** dependency? The mentioned **pngquant-bin** is somehow connect with **libpng** and in my case, installing it fixed the issue.

**Comment by robaxelsen** [comment] 2019-05-15 13:24
@krstic-duci thanks for investigating, and providing a solution to reported issue. Closing this, but feel free to open if problem persists.

**Closed by robaxelsen** 2019-05-15 13:24 UTC
Labels: bug

**Comment by callmesoul** [comment] 2021-01-28 06:27
i have same promise

- Node version: v12.18.2
- Platform:  windows 10

**Comment by callmesoul** [comment] 2021-01-29 01:58
I found that the problem is that `libpng` is used in `pngquant`, but the npm package of `libpng` only uses linux and mac.
window needs to be downloaded and installed by yourself
http://gnuwin32.sourceforge.net/packages/libpng.htm
After installation, you can re-install `npm install`

**Comment by callmesoul** [comment] 2021-01-29 03:24
window system install  gridsome is to hard
