### ISSUE TITLE
Apollo GraphQL Support

### ISSUE THREAD

**Issue by rykersouthwick** [gridsome/gridsome#441] opened 2019-05-17 20:42 UTC
## Summary

Ability to use apollo graphql inside gridsome.

_for the record I love to use Apollo paired with Adonis.js
[article](https://scotch.io/tutorials/build-a-graphql-server-with-apollo-server-and-adonisjs)_

### Basic example

You would use gridsome the same way but it will pull data from the apollo graphql server

### Motivation

I think using apollo as an api that static hosted websites can use is the future.

**Comment by robaxelsen** [comment] 2019-05-19 09:06
Duplicate of #80. @rykersouthwick feel free to re-open if I have misunderstood your request. Otherwise please post any additional details in #80.

**Closed by robaxelsen** 2019-05-19 09:06 UTC
