### ISSUE TITLE
When querying all GhostPosts by an author from Ghost, GhostPages show up as empty nodes

### ISSUE THREAD

**Issue by DenzoNL** [gridsome/gridsome#1319] opened 2020-08-23 15:31 UTC
## Description

So I've just discovered this while fleshing out my website. After I added a Page in Ghost CMS, my GhostAuthor template started throwing errors in `gridsome develop` and `gridsome build` started failing. The issue turned out to be that using the `belongsTo` relationship in GraphQL also returns GhostPages as empty nodes. Vice-versa, when querying for `GhostPage` belong to an author, all `GhostPost` are returned as empty nodes.

### Steps to reproduce

Providing a reproduction repo requires me to set up an additional Ghost Instance, but since the bug is fairly simple, I don't think it will be necessary, though. If required though, please send a message.

1. Create a new gridsome project with `@gridsome/source-ghost` configured.
2. Using the same author, create a new Post and a new Page in Ghost CMS.
3. In the GraphQL Playground, query the author and their posts. This query assumes the configured template path is `/:slug` and the author's slug is `test-author`:

```
{
  ghostAuthor(path: "/test-author/") {
    belongsTo {
      edges {
        node {
          ...on GhostPost {
            title
            slug
            primary_author {
              name
              path
            }
          }
        }
      }
    }
  }
}
```

### Expected result

```
{
  "data": {
    "ghostAuthor": {
      "belongsTo": {
        "edges": [
           {
            "node": {
              "id": "5f07995fc4b76000012f11d8",
              "title": "Test post,
              "slug": "test-post",
              "primary_author": {
                "name": "Test Author",
                "path": "/test-author/"
              }
            }
          },
        ]
      }
    }
  }
}
```

### Actual result

```
{
  "data": {
    "ghostAuthor": {
      "belongsTo": {
        "edges": [
           {
            "node": {
              "id": "5f07995fc4b76000012f11d8",
              "title": "Test post,
              "slug": "test-post",
              "primary_author": {
                "name": "Test Author",
                "path": "/test-author/"
              }
          },
          {
            "node": {} // An empty node is returned for each Page belonging to this author
          }
        ]
      }
    }
  }
}
```

### Environment

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.19041.423.0), Chromium (84.0.522.63)
  npmPackages:
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0
    @gridsome/source-ghost: ^0.4.0 => 0.4.0
    gridsome: ^0.7.0 => 0.7.19
    gridsome-plugin-ackee: ^0.0.1 => 0.0.1
    gridsome-plugin-manifest: ^0.3.5 => 0.3.5
    gridsome-plugin-tailwindcss: ^3.0.1 => 3.0.1
```

**Comment by hjvedvik** [comment] 2020-08-23 21:56
The `belongsTo` field will return all nodes that have a reference to it, even though the type has no fields specified in the query. But you can try to filter by type and see if it will help. Like this:

```gql
{
  ghostAuthor(path: "/test-author/") {
    belongsTo(filter: { typeName: { eq: GhostPost } }) {
      edges {
        node {
          ...on GhostPost {
            title
```

**Comment by Prince007-bd** [comment] 2020-08-23 22:02
Hi ok

**Comment by DenzoNL** [comment] 2020-08-24 16:25
> ```graphql
> (filter: { typeName: { eq: GhostPost } })
> ```

Thanks a bunch, this seems to work! I'm not sure now if what I have reported is a bug or working as intended. Perhaps it could be useful to add this to the docs. Either way, I'll leave it up to you to close if if you feel it is not a bug :)

**Comment by hjvedvik** [comment] 2020-08-26 22:26
It is working as intended, so I'll close it :) But I agree that the docs could be clearer about it. I'll add it to my todo-list.

**Closed by hjvedvik** 2020-08-26 22:26 UTC
